### ISSUE TITLE
Cannot send text-mode commands to TinyG

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-ver2#15]
On tab "hardware setup" I cannot send commands to TinyG - it gives exceptions with JSON parser.

Example commands:
`$sys
$x`

Sending JSON commands works but is less convenient to type - example:
`{"sys":""}` 

Also, if one makes a typo, the parser will also crash and console will be broken afterwards.

**Comment by thethereza** [comment]
not sure what the failure mode is when you enter something wrong - can you demonstrate an example?

**Comment by mrandt** [comment]
I think the problem is parsing the response from TinyG.

To replicate:
1. Turn on "Show Raw Commands"
2. Send a JSON command, such as `{"ver":""}` -> works
3. Send a text command such as `$ver`or `$` -> exception
4. After exception is thrown, communication becomes instable: jogging fails, valid commands are not executed again -> have to reset TinyG and restart application to work again

Screenshot:
![console](https://cloud.githubusercontent.com/assets/10500490/8727725/7f151abc-2be1-11e5-94cc-535522b29d1e.png)

Copy & pasted console output for a similar test is also below - notice how the second time I ask for version info using JSON command (after getting exception) it no longer works either:

```
> {"ver":""}
{"r":{"ver":null},"f":[1,100,11,9698]}
<= r
> $
########## Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 205
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
> $ver
########## Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 205
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
########## Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 205
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
> {"ver":""}
########## Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 205
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
```
