### ISSUE TITLE
TinyG communication broken in SVN Rel 25

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-ver2#33]
In latest SVN release 25, communication with TinyG is broken - get exceptions when trying to connect from host software and executing commands - see below:

![2015-07-20 12_45_41-liteplacer](https://cloud.githubusercontent.com/assets/10500490/8774775/165efc46-2ee2-11e5-86dc-da9a3119378a.png)

![2015-07-20 12_44_31-liteplacer](https://cloud.githubusercontent.com/assets/10500490/8774777/1a8c9d50-2ee2-11e5-9d56-c50ae715a817.png)

Further log:

```
{"r":{"sr":{"posx":-0.500,"posy":-0.500,"posz":0.000,"posa":0.000,"feed":150.00,"vel":0.00,"unit":1,"coor":1,"dist":0,"frmo":1,"stat":3}},"f":[1,0,10,1927]}
{"r":{"fv":0.970,"fb":438.02,"hp":1,"hv":8,"id":"3X3566-SXB","msg":"SYSTEM READY"},"f":[1,0,0,4089]}
{"qr":32,"qi":1,"qo":1}
########## System.NullReferenceException: Object reference not set to an instance of an object.
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 178
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
########## System.InvalidOperationException: The port is closed.
   at System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 71
> {"sr":""}
{"r":{"sr":{"posx":0.000,"posy":0.000,"posz":0.000,"posa":0.000,"feed":0.00,"vel":0.00,"unit":1,"coor":1,"dist":0,"frmo":1,"stat":1}},"f":[1,0,10,1190]}
{"sr":{"posx":0.000,"posy":0.000,"posz":0.000,"posa":0.000,"feed":0.00,"vel":0.00,"unit":1,"coor":1,"dist":0,"frmo":1,"stat":1}}
########## System.NullReferenceException: Object reference not set to an instance of an object.
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 187
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
> {"xjm":""}
{"r":{"xjm":1000},"f":[1,0,11,1454]}
> {"xvm":""}
{"r":{"xvm":10000},"f":[1,0,11,3029]}
> {"xsv":""}
{"r":{"xsv":2000},"f":[1,0,11,8943]}
> {"xsn":""}
{"r":{"xsn":3},"f":[1,0,11,6374]}
> {"xjh":""}
{"r":{"xjh":2000},"f":[1,0,11,5217]}
> {"xsx":""}
{"r":{"xsx":2},"f":[1,0,11,8632]}
> {"1mi":""}
{"r":{"1mi":8},"f":[1,0,11,7985]}
> {"1sa":""}
{"r":{"1sa":0.900},"f":[1,0,11,7161]}
> {"1tr":""}
{"r":{"1tr":40.0000},"f":[1,0,11,2474]}
> {"yjm":""}
{"r":{"yjm":1000},"f":[1,0,11,8174]}
> {"yvm":""}
{"r":{"yvm":10000},"f":[1,0,11,1999]}
> {"ysn":""}
{"r":{"ysn":3},"f":[1,0,11,48]}
> {"ysx":""}
{"r":{"ysx":2},"f":[1,0,11,9141]}
> {"yjh":""}
{"r":{"yjh":2000},"f":[1,0,11,1938]}
> {"ysv":""}
{"r":{"ysv":2000},"f":[1,0,11,5664]}
> {"2mi":""}
{"r":{"2mi":8},"f":[1,0,11,1659]}
> {"2sa":""}
{"r":{"2sa":0.900},"f":[1,0,11,9295]}
> {"2tr":""}
{"r":{"2tr":40.0000},"f":[1,0,11,2225]}
> {"zjm":""}
{"r":{"zjm":500},"f":[1,0,11,7926]}
> {"zvm":""}
{"r":{"zvm":5000},"f":[1,0,11,9156]}
{"r":{"zsn":3},"f":[1,0,11,3721]}
> {"zsn":""}
> {"zsx":""}
{"r":{"zsx":2},"f":[1,0,11,2815]}
> {"zjh":""}
{"r":{"zjh":500},"f":[1,0,11,2724]}
> {"zsv":""}
{"r":{"zsv":600},"f":[1,0,11,255]}
> {"3mi":""}
{"r":{"3mi":8},"f":[1,0,11,5332]}
> {"3sa":""}
{"r":{"3sa":1.800},"f":[1,0,11,1431]}
> {"3tr":""}
{"r":{"3tr":8.0000},"f":[1,0,11,7613]}
> {"ajm":""}
{"r":{"ajm":5000},"f":[1,0,11,2237]}
> {"avm":""}
{"r":{"avm":30000},"f":[1,0,11,7266]}
> {"4mi":""}
{"r":{"4mi":4},"f":[1,0,11,5749]}
> {"4sa":""}
{"r":{"4sa":1.800},"f":[1,0,11,401]}
> {"4tr":""}
{"r":{"4tr":160.0000},"f":[1,0,11,2085]}
> {"4po":""}
{"r":{"4po":1},"f":[1,0,11,3674]}
> {"zsn",3}
{"r":{"zsn":3},"f":[1,0,10,3720]}
> {"zsx",2}
{"r":{"zsx":2},"f":[1,0,10,2814]}
> {"zzb",2}
{"r":{"zzb":2.000},"f":[1,0,10,6309]}
########## System.Exception: bad map for field zzb
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at LitePlacer.FormMain.ValueUpdater(String item, String value) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\MainForm.cs:line 1073
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 273
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
########## System.IO.IOException: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 71
########## System.InvalidOperationException: The port is closed.
   at System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 71
> {"sr":""}
{"r":{"sr":{"posx":0.000,"posy":0.000,"posz":0.000,"posa":0.000,"feed":0.00,"vel":0.00,"unit":1,"coor":1,"dist":0,"frmo":1,"stat":1}},"f":[1,0,10,1190]}
> {"xjm":""}
{"r":{"xjm":1000},"f":[1,0,11,1454]}
> {"xvm":""}
{"r":{"xvm":10000},"f":[1,0,11,3029]}
> {"xsv":""}
{"r":{"xsv":2000},"f":[1,0,11,8943]}
> {"xsn":""}
{"r":{"xsn":3},"f":[1,0,11,6374]}
> {"xjh":""}
{"r":{"xjh":2000},"f":[1,0,11,5217]}
> {"xsx":""}
{"r":{"xsx":2},"f":[1,0,11,8632]}
> {"1mi":""}
{"r":{"1mi":8},"f":[1,0,11,7985]}
> {"1sa":""}
{"r":{"1sa":0.900},"f":[1,0,11,7161]}
> {"1tr":""}
{"r":{"1tr":40.0000},"f":[1,0,11,2474]}
> {"yjm":""}
{"r":{"yjm":1000},"f":[1,0,11,8174]}
> {"yvm":""}
{"r":{"yvm":10000},"f":[1,0,11,1999]}
> {"ysn":""}
{"r":{"ysn":3},"f":[1,0,11,48]}
> {"ysx":""}
{"r":{"ysx":2},"f":[1,0,11,9141]}
> {"yjh":""}
{"r":{"yjh":2000},"f":[1,0,11,1938]}
> {"ysv":""}
{"r":{"ysv":2000},"f":[1,0,11,5664]}
> {"2mi":""}
{"r":{"2mi":8},"f":[1,0,11,1659]}
> {"2sa":""}
{"r":{"2sa":0.900},"f":[1,0,11,9295]}
> {"2tr":""}
{"r":{"2tr":40.0000},"f":[1,0,11,2225]}
> {"zjm":""}
{"r":{"zjm":500},"f":[1,0,11,7926]}
> {"zvm":""}
{"r":{"zvm":5000},"f":[1,0,11,9156]}
> {"zsn":""}
{"r":{"zsn":3},"f":[1,0,11,3721]}
> {"zsx":""}
{"r":{"zsx":2},"f":[1,0,11,2815]}
> {"zjh":""}
{"r":{"zjh":500},"f":[1,0,11,2724]}
> {"zsv":""}
{"r":{"zsv":600},"f":[1,0,11,255]}
> {"3mi":""}
{"r":{"3mi":8},"f":[1,0,11,5332]}
> {"3sa":""}
{"r":{"3sa":1.800},"f":[1,0,11,1431]}
> {"3tr":""}
{"r":{"3tr":8.0000},"f":[1,0,11,7613]}
> {"ajm":""}
{"r":{"ajm":5000},"f":[1,0,11,2237]}
> {"avm":""}
{"r":{"avm":30000},"f":[1,0,11,7266]}
> {"4mi":""}
{"r":{"4mi":4},"f":[1,0,11,5749]}
> {"4sa":""}
{"r":{"4sa":1.800},"f":[1,0,11,401]}
> {"4tr":""}
{"r":{"4tr":160.0000},"f":[1,0,11,2085]}
> {"4po":""}
{"r":{"4po":1},"f":[1,0,11,3674]}
> {"zsn",3}
{"r":{"zsn":3},"f":[1,0,10,3720]}
> {"zsx",2}
{"r":{"zsx":2},"f":[1,0,10,2814]}
> {"zzb",2}
{"r":{"zzb":2.000},"f":[1,0,10,6309]}
########## System.Exception: bad map for field zzb
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at LitePlacer.FormMain.ValueUpdater(String item, String value) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\MainForm.cs:line 1073
   at LitePlacer.CNC.InterpretLine(String line) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\CNC.cs:line 273
   at LitePlacer.SerialComm.DataReceived(Object sender, SerialDataReceivedEventArgs e) in c:\Users\Malte\Documents\svn\liteplacerrmod\trunk\LitePlacer\SerialComm.cs:line 81
```

**Comment by mrandt** [comment]
This appears to be fixed in SVN release 26, thus I am closing the issue.
